### ISSUE TITLE
PlayerConfig Aktualisieren

### ISSUE THREAD

**Issue by paflov** [verona-interfaces/player#1]
Es fehlt ein Kommando um die PlayerConfig von Host-Seite aus zu aktualisieren. Diese wird nur einmal beim Starten der Unit mit vopStartCommand geschickt.

Konkretes Beispiel aus dem Testcenter Bereich:
Wir sind in einer Unit und folgende Block ist noch gesperrt. Bei starten der Unit schickt der Host also playerConfig.enabledNavigationTargets = ['previous', 'first'] mit - ein 'next' gibt es ja nicht. Entsprechend blendet der Player kein 'next' ein. Nun wird auf Grund der gegebenen Antworten der nächste Block freigeschaltet - doch der Player blendet immer noch keinen Next-Button ein.

Analoges *könnte* ich mir zumindest für logPolicy, pagingMode und printMode gelten, wenn man an einen Host wie das Studio oder das Testbed denkt.

Vorschlag:
vopPlayerConfigChanged: {
  sessionId,
  playerConfig
}

**Comment by mechtelm** [comment]
Umgesetzt in Version 6.0
