### ISSUE TITLE
Alternative zur Einbindung des Players in einem Testcenter

### ISSUE THREAD

**Issue by HoffmannP** [verona-interfaces/player#11]
Wir könnten anstelle oder alternativ zum iframe auch eine WebComponent auf Basis der Shadow-DOM verwenden. Die Gefahr ist jedoch, dass das Javascript der Aufgabe auf das DOM des Testcenters zugreift, geschützt ist leider nur die Gegenrichtung.
Darüber hinaus müssten geklärt werden, über welchen Kanal die Kommunikation zwischen TC<->PL verläuft. Das Protokoll kennen wir schon ;-)

Gedanken, Ideen?

**Comment by d-schiffner** [comment]
Die Kommunikation kann identisch zu der bisherigen sein (Siehe PR #12 )

Die Gefahr ist natürlich vorhanden, bleibt aber prinzipiell die Frage, welche Maßnahmen seitens des Testcenters gemacht werden müssen / sollten.

Ist es denn zu erwarten, dass HTML geladen wird, welches mutwillig das Testcenter angreift?

**Comment by HoffmannP** [comment]
Mutwilig eher nicht, der Fokus liegt auf defensivem Programmieren um Unaufmerksamkeiten vorzubeugen
