### ISSUE TITLE
Rename `sessionId` to `session`

### ISSUE THREAD

**Issue by HoffmannP** [verona-interfaces/player#13]
In allen Transaktionen `sessionId` => `session` umbenennen

**Comment by paflov** [comment]
Warum? Bei einem Bezeichner `session` würde man ja auch Session_daten_ erwarten.

Siehe auch

- https://de.wikipedia.org/wiki/Sitzungsbezeichner Abschnitt "Speicherung der Sessioninformationen auf dem Server"

Bei Server-Client Kommunikation (was freilich nicht dasselbe ist) werden Variablen wie JSESSIONID (Java EE), PHPSESSID (PHP), and ASPSESSIONID (Microsoft ASP) verwendet. 

Man könnte auch Diskutieren, ob es sich nicht vielmehr um ein Sessiontoken handelt. Siehe auch:

- https://security.stackexchange.com/questions/81756/session-authentication-vs-token-authentication
- https://stackoverflow.com/questions/17748868/session-id-vs-token

Ich persönlich würde sagen `SessionID` ist schon OK. Eine alernative wäre `sid`.

.
