### ISSUE TITLE
Besserer Name für `Testcenter`

### ISSUE THREAD

**Issue by HoffmannP** [verona-interfaces/player#14]
Das Wort "Testcenter" hängt an der Idee, dass ein Test durchgeführt wird. Tatsächlich existieren jedoch auch andere Prozesse in denen ein Item dargestellt wird. "Host" erscheint mir wiederum ein kleines bisschen zu allgemein, wobei das im Zweifelsfall auch ginge.

Gibt es Vorschläge?

**Comment by paflov** [comment]
In welchem Zusammenhang stehen diese Begriffe in Konkurrenz? 

**Testcenter** ist für mich als Bezeichnung eines bestimmten _Anwendungstypen_ - nämlich eine Anwendung die Verona-Kompatible Unit-Players nutzt um Test-Sequenzen durchzuführen und zu steuern. Man könnte auch Test-Controller dazu sagen oder Test-Kontrollcenter, Test-Operator oder was auch immer dazu sagen.

**Host** bezeichnet aus Sicht eines solchen Verona-Kompatible Unit-Players jede Anwendung, die ihn einbettet und nutzt - das kann ein Testcenter, aber auch z. B. eine Anwendung zur Gestaltung von Aufgaben (die man Test-Composer, Test-Studio etc. nennen könnte) oder etwas ganz anderes sein.

**Comment by mechtelm** [comment]
In den Dokumenten ist jetzt stets von der "host application" die Rede, der Begriff "Testcenter" ist also entfernt.
