### ISSUE TITLE
vopUnitNavigationRequestedNotification - targets nicht richtig beschrieben.

### ISSUE THREAD

**Issue by paflov** [verona-interfaces/player#22]
[In der Doku](https://github.com/verona-interfaces/player/blob/f753745d15b482c5426f29fd6ab4420194c4046a/api/playerapi.yaml#L154) heißt es, die targets hießen "next", "previous", "first", "last" und "end". Damit es funktioniert, müssen sie aber  "#next", "#previous", "#first", "#last" und "#end",  also mit vorangestellter Raute lauten. Ist das ein Fehler in der Doku, oder ein Implementierungsfehler im Testcenter?

**Comment by mechtelm** [comment]
Es gab mal einen Plan, dass für die Unit-Navigation ein direkter Sprung zu einer bestimmten Unit erlaubt ist und dann beim Navigieren-Request diese Unit-Id angegeben wird. Zur Markierung eines relativen Ziels diente dann das Hash-Zeichen,

Diese Idee finde ich jetzt nicht mehr so gut. Daher auch die Änderung des Parameters von `targetRelative` in `target`. Ich wäre dafür, ohne Hash zu arbeiten und alle Hosts und Player umzustellen.

**Comment by rhenck** [comment]
Ich denke solange es keine konkrete Anforderung gibt zu bestimmten Units zu springen, brauchen wir das auch nicht erlauben.
Verstehe ich das richtig, dass der geänderte Parameter 'target' dann nur noch relative Ziele beschreibt? Könnte man dann evtl. auch bei targetRelative belassen, dann wird es deutlicher was der tut.

Habe da keine wirkliche Meinung zu. Wenn du dich entschieden hast, dann mach mal Tickets in den entsprechenden Projekten.

**Comment by mechtelm** [comment]
Wenn es im Moment nichts anderes als relativ gibt, muss man das nicht betonen. Sollten wir irgendwann als Target eine konkrete Unit-Id erlauben (was ich nicht hoffe), könnte man ein Präfix wieder einführen, also z. B. "#M2554EX". Das wäre dann auch ein Target.

**Comment by mechtelm** [comment]
Also # wird aktuell nicht im Interface verwendet.
