### ISSUE TITLE
vopStartCommand sollte auch den playerState enthalten

### ISSUE THREAD

**Issue by paflov** [verona-interfaces/player#23]
Das [vopStartCommand](https://verona-interfaces.github.io/player/#operation-publish-vopStartCommand) sollte auch den PlayerState enthalten, damit man z.B. die zuletzt besuchte Seite wieder herstellen kann!

**Comment by mechtelm** [comment]
Die spannende Frage hier ist, ob die zuletzt besuchte Seite vielleicht zum UnitState gehört. Ich denke nein. Es sollte der Testcontroller entscheiden, ob zur ersten (Standard) oder der zuletzt gewählten Seite gegangen wird. Sollte letzteres gewünscht sein, dann kann der Testcontroller locker mit [vopPageNavigationCommand](https://verona-interfaces.github.io/player/#operation-publish-vopPageNavigationCommand) nachsetzen.

**Comment by paflov** [comment]
Könnte nicht der PlayerState noch weiteres enthalten, dass man wieder herstellen möchte? Er darf doch theoretisch beliebige Felder enthalten. Klar kann kann man den State auch nachschieben, aber ich fände es eigentlich logischer, der beim Start-Command gleich mitzugeben? Oder was spricht dagegen?

**Comment by mechtelm** [comment]
mit v3.0 implementiert.
