### ISSUE TITLE
vopStartCommand könnte auch mitliefern, wo im Booklet man sich befindet

### ISSUE THREAD

**Issue by paflov** [verona-interfaces/player#24]
Noch ein Vorschlag für das `vopStartCommand`: Ein Feld `bookletContext` mit den möglchen werten `first`, `last`, `middle`, das angibt, wo im booklet sich die unit befindet - damit man die internen weiter/zurück-buttons ggf. ein- und ausblenden kann.

**Comment by paflov** [comment]
hat sich erlegit, das steht ja in der playerConfig!

**Comment by paflov** [comment]
Ach nee, da fehlt aber die Angabe `unitCount`, damit man feststellen kann ob man am Anfang oder am Ende ist...

**Comment by mechtelm** [comment]
Hm soll man dem Player erlauben, Unit-/Test-Navigation anzuzeigen? Dann könnte man `unit-navigation-next-enabled: true | false` und `unit-navigation-prev-enabled: true | false` einführen. Sollten dann auch die Labels der nächsten/vorherigen Units übergeben werden? Sollte man dann auch noch einen 'Test beenden'-Button erlauben oder unterbinden, dessen Label auch noch variabel sein sollte ('Befragung beenden')? Was ist mit 'An den Anfang', 'Ans Ende'?

Ich wäre doch dafür, grundsätzlich diese Navigation dem Host zu überlassen. Für den Notfall haben wir ja `vopUnitNavigationRequestedNotification`, aber eigentlich nur für den Notfall.

**Comment by paflov** [comment]
Was heißt denn für den Notfall? Entweder es gibt ein Feature im Standard oder nicht, oder? 

Ich hätte jetzt gedacht, es ist Player-Entwicklern durch `vopUnitNavigationRequestedNotification` erlaubt, eine Unit-Navigation in die Units reinzubauen (das wollte Berengar oder so ja unbedingt wenn ich mich recht erinnere), dann kann man auch ruhig die fehlenden Informationen mitliefern. 

> Dann könnte man unit-navigation-next-enabled: true | false und unit-navigation-prev-enabled: true | false einführen. 

Aktuell sind ja `next`, `previous`, `first`, `last`, und `end` mögliche Ziele - und mehr braucht man auch nicht. Man könnte sagen, der Host liefert mit, welche Ziele erlaubt sind und welche nicht, und optional labels. Ob diese Labels dann vom Player verwendet werden oder er eigene verwendet ist ja dann Entscheidung des Players.

Ich fänds auch vertretbar das Feature komplett zu streichen, dann sollte es `vopUnitNavigationRequestedNotification` auch nicht geben. Ich finds persönlich eigentlich nicht schlecht, wenn es das gibt; mit etwas Fantasie fallen mit da Anwendungsbeispiele ein, wenn man sich etwas eleganter designte oder ausgefallenere Hosts sich vorstellt z. B.

**Comment by mechtelm** [comment]
mit v3.0 implementiert.
