### ISSUE TITLE
responseProgress Werte definieren

### ISSUE THREAD

**Issue by paflov** [verona-interfaces/player#25]
Die möglichen Werte von `responseProgress` werden zwar als: `none`, `some`, `complete` und `complete-and-valid` [genannt](https://verona-interfaces.github.io/player/#operation-subscribe-vopStateChangedNotification), aber nicht weiter beschrieben. 
Insbesondere ist mit unklar was complete oder incomplete bedeutet. Bei Radio-Buttons okay, so lange *gar keiner* gewählt ist, ist das wohl incomplete, aber bei einem Textfeld. So bald mindestens ein Buchstabe drinsteht? Drei? Ich fände es logischer nur zwischen valid und invalid zu unterscheiden, was auch Eigenschaften sind, die HTML-Formulare hergeben.

**Comment by paflov** [comment]
Dazu kommt, das validität und vollständigkeit zwei verschiedene Dinge sind... oder es müsste noch `some-and-valid` geben.

**Comment by mechtelm** [comment]
Status `complete` bedeutet, dass alle Eingabe-Controls, die als `required` markiert sind, eine Eingabe erhalten haben. Status `some` bedeutet, dass es einige Eingaben gab.

Ein kluges (also normales) Formular erlaubt keine invaliden Eingaben. Die Werteübermittlung wird unterbunden, solange die Validierung nicht erfolgreich war. Sollte eine Unit also `complete` sein, dann ist sie auch gleichzeitig valide. Der Status `complete-and-valid` ist also überflüssig.

Zu Ankreuzfeldern: Wenn eine einzelne Checkbox als `required` markiert ist, dann bedeutet das, dass man ankreuzen muss, um ein valides Formular zu erhalten. Das kann z. B. eine Zustimmung zu Datenschutzverfahren sein.

Zu Texteingaben: Wenn als `required` markiert, dann genügt ein Zeichen. Zusätzlich kann man - sofern sinnvoll - eine Mindestlänge (und Maximallänge) fordern. Hat man eine Mindestlänge, aber ohne `required`, dann ist eine leere Eingabe valide, aber wenn eine Eingabe erfolgte, muss sie die Mindestlänge einhalten.

**Comment by paflov** [comment]
> Ein kluges (also normales) Formular erlaubt keine invaliden Eingaben. Die Werteübermittlung wird unterbunden, solange die Validierung nicht erfolgreich war. Sollte eine Unit also complete sein, dann ist sie auch gleichzeitig valide. Der Status complete-and-valid ist also überflüssig. 

Was ich dagegen einwenden könnte, ist, dass RestorePoint und UnitState jetzt ein und dasselbe sind. Und man ja vllt. auch invalide States übermitteln will, um sie nach einem eventuellen Neuladen wieder herstellen zu können. Mir fällt allerdings (noch) kein konkreter Fall ein, in das relevant sein könnte.

**Comment by mechtelm** [comment]
Dann darf man keine Validität außer `required` vorgeben. Sobald man eine Antwort für würdig erachtet, gespeichert zu werden, ist sie valide. Ob sie dann bei der Datenverarbeitung später noch als valide angesehen wird, ist für die Testsituation wurscht.

**Comment by mechtelm** [comment]
mit v3.0 implementiert.
