### ISSUE TITLE
Überflüssiges vopGetStateResponse?

### ISSUE THREAD

**Issue by paflov** [verona-interfaces/player#26]
Wozu gibt es eigentlich `vopGetStateResponse`? Könnte man auf ein `vopGetStateRequest` nicht einfach mit einem `vopStateChangedNotification` antworten?

**Comment by mechtelm** [comment]
`vopStateChangedNotification` liefert die Änderungen zu einem vorherigen State. `vopGetStateResponse` soll alles liefern. Oder? 

In einem Szenario, in dem das Schicken von Änderungen nicht über die Änderung, sondern über den Host ausgelöst wird, gibt es theoretisch kein `vopStateChangedNotification`. Vielleicht besser: `vopStateChangedNotification` und `vopGetStateResponse` ersetzen durch `vopState` des Players, wobei ein Parameter `range: 'changed-only' | 'full'` mitgeschickt wird?

**Comment by paflov** [comment]
> vopStateChangedNotification liefert die Änderungen zu einem vorherigen State. vopGetStateResponse soll alles liefern. Oder?

Stimmt. Hab ich auch genauso implementiert am Ende. Können wir eigentlich so lassen, ist glaube ich  klarer als mit dem Parameter.

**Comment by mechtelm** [comment]
mit v3.0 implementiert.
