### ISSUE TITLE
Muss `validPages` und `currentPage` in `playerState` Pflicht sein?

### ISSUE THREAD

**Issue by paflov** [verona-interfaces/player#27]
In `playerState` (`vopStateChangedNotification`) sind `validPages` und `currentPage` Pflicht. Bei Seitenlosen Units ist das eigentlich unnötige Information. Ich schlage daher vor diese Attribute freiwillig zu machen.

**Comment by mechtelm** [comment]
Finde ich gut.

**Comment by mechtelm** [comment]
mit v3.0 implementiert.
