### ISSUE TITLE
Fatalen Fehler im Player melden

### ISSUE THREAD

**Issue by paflov** [verona-interfaces/player#3]
Uns sind zwei Situationen bekannt, in denen fatale Fehler im Player auftreten können:
* geogebra kann nicht richtig geladen oder initialisiert werden
* Audios oder Videos können nicht richtig encodiert werden.

Wenn von der Darstellung eines solchen Elements (Video abgespielt zB) das Einblenden anderer Elemente abhängt, kann ein solcher Fehler dazu führen, dass niemals presentationProgress=complete erreicht werden kann. Sind entsprechende Restriktionen im Booklet gesetzt, kann man die Unit nicht mehr verlassen.

Es wäre gut, wenn die Verona-Schnittstelle einen Kanal bieten würde, über den ein Fataler Fehler gemeldet werden kann.
Dann könnte der Host reagieren, z. B.:
* einen log schreiben
* die Unit neuladen
* Complete-Restriktionen aufheben...

**Comment by mechtelm** [comment]
Finde ich gut. Das wäre dann z. B. `vopRuntimeErrorNotification` mit einem Payload `errorCode` und `errorMessage`? Und den code definieren wir noch?

**Comment by paflov** [comment]
Ja, z. B. Wobei ich als errorCode einen String aus einer definierten Liste verwenden würde, keinen numerischen Code, wie bei HTTP.

**Comment by mechtelm** [comment]
Umgesetzt in Version 6.0
