### ISSUE TITLE
Werden Antworten wirklich erst nach Bedarf geholt?

### ISSUE THREAD

**Issue by mechtelm** [verona-interfaces/player#33]
Brauchen wir `vopGetStateRequest`? Wir haben bisher stets die Anworten bei jeder Änderung geschickt. Der Grund liegt darin, dass in der Programmierung des Testcontrollers es sehr schwierig ist, auf `vopStateChangedNotification` mit vollem unitState zu warten. Die Anwendung ist u. U. in unsicherem Zustand.

Die Idee, die Antwortänderung anzukündigen ohne Payload, kam aus der Überlegung, dass der Payload zu groß sein könnte bei komplexen Antworten. Aber durch die Einführung von dataParts beim unitState kann der Player diesem Problem begegnen: Werden die Antworten bulky, dann teilt er sie einfach auf.

Vorschlag: Streichen. Entsprechend muss `stateReportPolicy` entfernt werden (Parameter im vopStartCommand).

**Comment by rhenck** [comment]
"Der Grund liegt darin, dass in der Programmierung des Testcontrollers es sehr schwierig ist, auf vopStateChangedNotification mit vollem unitState zu warten. Die Anwendung ist u. U. in unsicherem Zustand."
Den Satz verstehe ich nicht. Kannst du das noch weiter begründen? Und was heisst unsicherer Zustand?

Soweit ich das verstehe, finde ich den Vorschlag gut, wir können das gerne streichen. Komplexitätsreduktion ist immer gut. :)

**Comment by mechtelm** [comment]
Wenn man (übrigens beim Editor analog) lazy state reporting einschaltet, weiß man nur, dass es Änderungen gab. Wenn dann der User woanders hin will, springt der routing guard an und kümmert sich um das Speichern, beim Editor nach Nachfrage. Dann schickt er also einen voxGetStateRequest ans Modul und wartet. Da das kein Funktionsaufruf ist und kein Api-Call, wartet er einfach nur, d. h. irgendwo ist registriert, dass es einen Routingwunsch gibt, aber nix weiter. Solange kann das Routing nicht freigegeben werden, der Guard hängt. Irgendwann kommt der State und man kann das Routing freigeben. Man muss also den Guard async deklarieren, was er sonst nicht wäre.

Da das doof ist, praktizieren wir das einfach nicht. Sowohl unser Testcontroller als auch der Editorcontroller fordern eager reporting. Der Editorcontroller sichert sogar nochmal ab, falls der payload in [voeDefinitionChangedNotification leer ist](https://github.com/iqb-berlin/studio-lite/blob/5276380784f866122a90117a0c9397b33620a9b8/apps/frontend/src/app/workspace/unit/unit-editor/unit-editor.component.ts#L69) und fordert gleich nochmal an (könnte eine Endlos-Loop sein hm...).
