### ISSUE TITLE
X.type Kennung überarbeiten

### ISSUE THREAD

**Issue by HoffmannP** [verona-interfaces/player#4]
1. Ich schlage vor das Prefix der Typenbezeichnung der Nachrichten von
```
vo.(From|To)Player.
```
zu
```
verona.vid.
```
zu ändern. Namespacing über Organisationsname und Projektname ist ein gängiges Verfahren (vgl. z.B. Java-Klassen-Bezeichnungen), die Richtung der Nachricht muss imho nicht eigenständig kodiert werden.

2. Die eigentliche Bezeichnung der eigentlich ist uneinheitlich, es finden sich das Suffix `Transfer`und `Notification` sowie `Request`, ein Imperativ `Navigate` und zwei Stati `Ready`, `Started`. Ich schlage folgende Bezeichnungen vor:
```
ReadyNotification -> requestingUnit
DataTransfer -> LoadUnit
StartedNotification -> Started
ChangedDataTransfer -> Changed
NavigateToPage -> Navigate
PageNavigationRequest -> requestingNavigation
UnitNavigationRequest -> requestingTermination
```
Immer wenn TC antworten soll beginnt der Messagetype mit "requesting", die Messagetypes des TC als verantwortliche Einheit hingegen sind Imperative da der Player reagieren muss. Statusmeldungen des Players sind adjektivierte Verben.

**Comment by mechtelm** [comment]
1. Prefix: Sollte es Nachrichten geben, die bei den verschiedenen Schnittstellen gleichlautend verwendet werden, dann reicht als Projekt vid. Sollte es pro Schnittstelle unterschiedliche Nachrichten-IDs geben, sollte "Player" im Projekt auftauchen, also z. B. vpid.
2a. ReadyNotification: Der Player requested nichts, sondern teilt nur Bereitschaft mit. Es wird Player geben, die keine weitere Unit-Definition erwarten, weil sie so speziell sind, dass alles Nötige schon im Player definiert ist. Der Player-Host entscheidet, ob er etwas schickt oder nur einen Log-Eintrag vornimmt. Daher sollte es bei der Information an den Host bleiben.
2b. DataTransfer: Yo was ist die Unit? In diesem Fall werden Unitdefinition und ggf. ein vorheriger RestorePoint übergeben. Naja, könnte man auch Load nennen, aber Load impliziert eine Aktivität des Players, was es nicht ist. Es ist ein Push des Hosts.
2c. Started - yo meinetwegen
2d: Changed: Das sieht für mich so aus, als würde der Player melden, dass sich etwas geändert hat (so wie das Autoren-Modul meldet "ChangedNotification"). Es ist aber mehr, nämlich das Schicken eines Pakets mit den geänderten Daten.
2e. Navigate: Ok, wenn klar ist, dass es ein Befehl ist vom Host an den Player ist. Da die Richtung in Deinem Vorschlag rausgenommen ist, bleibt das offen, und das wäre nicht gut.
2f. Page/Unit-Navigation Request: Auch hier ist die Richtung wichtig, denn der Player darf nicht navigieren, sondern nur anfragen. Unit-Navigation ist viel mehr als Terminate, sondern auch next unit und prev unit und first unit usw.

**Comment by paflov** [comment]
1.
Namespacing über Organisationsname und Projektname finde ich gut. Unsere wären dann z. B.

* `iqb.testcenter`
* `iqb.graficPlayer`
usw. Richtig?

2.
Also, als jemand der später einstieg, fand ich die alten Begriffe gar nicht intuitiv als ich meinen Player gebastelt habe, und finde es daher gut, dass es darüber noch Diskussion gibt. Im Zentrum steht die Frage  die Frage, ob man die Begriffe aus Perspektive von Player oder Host aus formuliert. Dahinter steht die fast philosophische Frage, wen man hier als (handelndes) Subjekt und wen als Objekt ansieht. Die wirkt zunächst spitzfindig, kann aber durchaus Auswirkungen auf manche Implementationen haben. 

Zunächst fand ich deinen Ansatz sehr überzeugend, alle Begriffe so zu wählen, dass sie von der selben Perspektive aus gedacht werden (in dem Fall vom Player), und dann nur konsequent, die Richtung wegzulassen. 
Leider finde ich die neuen Vorschläge allerdings kein Stück verständlicher als die alten um ehrlich zu sein. Daher habe ich über Vermessungsvorschläge nachgedacht und bin am Ende mit einem ganz neuen Vorschlag geendet.

Das Beispiel ReadyNotification beinhaltet eigentlich schon den ganzen Konflikt: Sieht man den Player als aktiv handelndes Subjekt an, so ist er es, der die Unit (zu dem Begriff in dem Zusammenhang noch mal weiter unten) anfordert und nicht Bescheid sagt, dass er fertig ist. Würde man eher, wie Martin, sagen, es handelt sich um einen Push des Hosts, der nur "zufällig" durch die Ready-Notification ausgelöst wird, macht DataTransfer als Begriff natürlich Sinn. Daraus ergibt sich die Frage: Würde ein hypothetisches Setup, in dem es keine Ready-Notification gibt (weil z. B. der Player synchron mit dem Host geladen worden ist), und mit dem Einspeisen der Unit anfängt im Sinne unseres Protokolls legal sein? Lautet die Antwort Ja, kann das Wording in Richtung Ready-Notification gehen, lautet sie nein, in Richtung requestingUnit. Daraus ergibt sich die allgemeinere Grundsatzfrage - weiß nicht ob ihr das schon beschlossen habt, bin ja erst dazu gekommen - ob die Spezifikation das genaue Kommunikations-Protokoll mit umfasst oder "nur" die verschiedenen Nachrichten-Typen.

Meinem Vorschlag liegen folgende Überlegungen zu Grunde: 
- Jeder Message-Typ sollte ein vollständiger Satz sein. 
- Mein Vorschlag nach langem hin- und her wäre, beide, Host und Player, als mögliche Subjekte anzusehen. 
- Die Messages sind dann immer als Aufforderungen an den jeweils anderen zu sehen, also immer Imperative.
- Daher nehme ich das Richtungs-Prefix wieder rein, damit immer klar ist, an wen die Aufforderung geht - wer das Subjekt des Satzes ist.
- Der Messagetyp setzt sich dann aus Verb und Objekt zusammen.
- Das Objekt ist meistens `Entity`, was nicht nur eine Unit an sich meint, sondern die Unit in einem bestimmten (Bearbeitungs-)Zustand (restorePoint). Wirklich zufrieden bin ich mit diesem Begriff aber noch nicht.


Und das sind letztlich meine aktuellen Vorschläge:

*  `FromPlayer.ReadyNotification` -> `host.getEntity`

Stimme Martin zwar zunächst zu, dass `requestingUnit` an sich nicht ganz das richtige ist, weil gar nicht sicher ist, ob Unit-Daten erforderlich sind. Andererseits ist eine schlichte Ready-Notification auch sehr missverständlich, da Notification impliziert, dass nichts zurück kommt und in den meisten Fällen werden hier Unit-Daten oder sogar RestorePoints kommen. Im Falle von Single-Unit-Playern wäre die zu ladende Entity eben leer (oder nur ein RestorePoint). Zudem würden Single-Unit-Player gar eigentlich keine ReadyNotification brauchen, sondern direkt mit StartedNotification anfagen!

* `ToPlayer.DataTransfer` -> `player.showEntity`

Load als Imperativ an den Player ginge schon, finde ich, denn den Vorgang, die übergebenen Daten (das Objekt in dem "Satz" load) zu "rendern" wäre auch eine Aufforderung an den Player. Noch deutlicher macht es show.

* `FromPlayer.StartedNotification` -> `host.updateEntity`

Ist dies nicht letztlich nur eine spezialisierte Form von `ChangedDataTransfer`?

* `FromPlayer.ChangedDataTransfer` -> `host.updateEntity`

Was soll der Host tun? Die Veränderungen zur Kenntnis nehmen.

* `ToPlayer.NavigateToPage` -> `player.navigate`

* `FromPlayer.PageNavigationRequest` ->  `host.requestNavigation`

In den Specs heißt es

> The Player requests the Testcenter to check and send a NavigateToPage.

Daher würde ich zunächst sagen, sollte das Verb genau das sein:  `host.checkNavigation`. Allerdings impliziert `check`, dass ein Ergebnis des Checks zurück kommt (ein Wahrheitswert z. B.) und nicht eine Navigations-Aufforderung. Player-Entwickler könnten das missverstehen und zum Beispiel das Anzeigen von Navigationsbuttons von diesem Check abhängig machen und sich wundern warum sofort navigiert wird. Am Ende ist der ursprüngliche Begriff dann noch der passendste: `host.requestNavigation`).

* `FromPlayer.UnitNavigationRequest` -> `host.changeEntity`

Ich stimme zu, dass es klarer ist, wenn man den Begriff `navigate` auf die Seiten innerhalb einer Aufgabe beschränkt. Daher schlage ich für die Navigation zwischen Aufgaben - sofern wir sie überhaupt erlauben, aber dass ist eine andere Diskussion) den Begriff `host.changeEntity` vor.

**Comment by mechtelm** [comment]
Namespacing sollte keine Organisation enthalten, denn die Schnittstelle ist ja allgemein und wird von allen genutzt. Man sollte den Bezug zum Projekt (Verona) und zur Schnittstelle (Player, Authoring Tool, Response Coding, Response Scheme Editor usw.) aufnehmen.

Die Schnittstelle kann nicht nur die Datentypen umfassen, es müssen alle Teile der Kommunikation geregelt werden.

Der Souverän ist stets der Host. Der Player kann etwas senden (Infos oder Antwortdaten), aber was wann passieren soll, entscheidet der Host. Der Player kann nicht wissen, wann etwas womit passieren soll. Erst wenn der Host entscheidet, dass die Unit-Bearbeitung starten soll, schickt er die Daten. Die ReadyNotification ist dafür nur eine Voraussetzung (der Host muss ja wissen, ob der Player bereit ist). Dem Player kann es egal sein, ob er nur vorsichtshalber gestartet wurde oder ob er tatsächlich irgendwann eine Unit-Definition bekommt. Außerdem kann es sein, dass mit dem einmal gestarteten Player mehrere Units gefahren werden, d. h. der Player bekommt regelmäßig neue Unit-Definitionen und verwirft alles vorherige.

Also der Host steuert, der Player informiert.

**Comment by paflov** [comment]
Dass der Souverän ausschließlich der Host, ist ein Standpunkt. Nimmt man den an, sind meine Vorschläge natürlich nicht sinnvoll. Dann würde mich aber interessieren, was @HoffmannP dazu sagt - denn dessen Vorschläge gehen ja von einem Player als (alleinigem) Souverän aus. Ich denke in dieser Frage muss Einigkeit herrschen, sonst wird man keine sinnvollen Begriffe finden und sich immer im Kreis drehen.

Mein einziges Problem mit dem Host als einziges Subjekt ist, dass Player Seiten- und (aber das ist auch so eine Sache für sich) Unit-Navigations Elemente enthalten können - und damit doch zum Subjekt wird. Als ich versucht habe, alle Meldungen des Players passiv als Statusmeldungen zu formulieren, bin ich genau darüber gestolpert. Und dann endet man eben bei linguistischen Hilfskonstrukten wie requestingPageNavigation, die für potentielle Anwender sehr verwirrend sind.
