### ISSUE TITLE
vopStateChangedNotification -> playerState: validPages sollte Array (statt Objekt) sein

### ISSUE THREAD

**Issue by rhenck** [verona-interfaces/player#4]
Objekte geben keine Garantie über die Reihenfolge, die ist hier aber wichtig.

~~Der Key ist hier, meinem Verständnis nach, nur eine Zahl mit dem Index. Da Arrays einen inhärenten Index haben, muss der nicht nochmal extra mitgeführt werden. Es bleibt also ein Array mit Strings für die Labels (string[]).~~

**Comment by rhenck** [comment]
Player können Seiten auslassen, daher müssen wir bei der Object-Struktur bleiben, allerdings verpackt in einen Array: { key: string, label: string }[]

**Comment by mechtelm** [comment]
Ja sollte ein Array sein, dann mit `id` und `label` als Objekteigenschaften. Allerdings würde ich ungern aus diesem Grund eine neue Major veröffentlichen - also das sollte warten, bis wir die nächste wichtige Anforderung haben.

**Comment by paflov** [comment]
#1 Wäre aus meiner Sicht eine solche wichtige Änderung...

**Comment by mechtelm** [comment]
Umgesetzt in Version 6.0
