### ISSUE TITLE
'type' fehlt in der API-Dokumentation

### ISSUE THREAD

**Issue by rhenck** [verona-interfaces/player#5]
Ausgehend von der Doku hier: https://verona-interfaces.github.io/player/#operation-publish-vopPageNavigationCommand

Aus Sicht des Players gibt es verschiedene Events die eingehen können: "vopStartCommand," "vopPageNavigationCommand" und "vopNavigationDeniedNotification". Damit diese behandelt werden können, muss unterschieden werden, um welches es sich handelt. Hierzu wird ein weiteres Feld "type" mitgesendet, welches den Namen des Events beinhaltet, z.B. "vopStartCommand".

Dieser Parameter taucht in der Dokumentation nicht auf.

Falls ich hier einen Denkfehler habe, bitte ich um Aufklärung.

**Comment by mechtelm** [comment]
Im Kommunikationsschema laut asyncAPI wird dieser Eintrag als ID der Operation bzw. Message bezeichnet. In postMessage() ist es zwar kein separater Teil des data-Objektes, aber ein notwendiger. Alles andere - sog. 'Payload', ist dann das Objekt, was als eine Art body der Message behandelt und daher dokumentiert wird. Ich fände es verwirrend, wenn wir das als Teil des Payloads nochmal deklarieren.

**Comment by rhenck** [comment]
> Im Kommunikationsschema laut asyncAPI wird dieser Eintrag als ID der Operation bzw. Message bezeichnet. In postMessage() ist es zwar kein separater Teil des data-Objektes, aber ein notwendiger. Alles andere - sog. 'Payload', ist dann das Objekt, was als eine Art body der Message behandelt und daher dokumentiert wird. Ich fände es verwirrend, wenn wir das als Teil des Payloads nochmal deklarieren.

Also ich verstehe die Ausführungen so, dass jede Message eine ID hat und diese implizit Teil der Payload ist, welcher nicht nochmal explizit aufgeführt werden soll, weil dies verwirren könnte.

Aus eigener Erfahrung in der Entwicklung der Aspect-Module, kann ich berichten, dass das Gegenteil der Fall war. Im Editor und Player wurde der "type" Parameter unterschiedlich hergeleitet.
Der Player hat durch Ausprobieren von der Existenz und dem Inhalt des Parameters erfahren und diesen dem Interface (welches ansonsten 1zu1 der Dokumentation entspricht) hinzugefügt (siehe bspw. hier: https://github.com/iqb-berlin/verona-modules-aspect/blob/0da731090784cd9cbfd5c1679f28e1c20e8fd593/projects/player/modules/verona/models/verona.ts#L47)
Der Editor widerum hat (fälschlicherweise) die API-Events vom Typescript-Interface "Event" erben lassen, welches zufälligerweise (!) einen Parameter "type" hat. Dieser war aber nicht gemeint und hat später zu Folgeproblemen geführt.

Auch in der Entwicklung der Speedtest-Module, musste sich dieses Wissen erneut erarbeitet werden.

Dies verdeutlicht hoffentlich, dass es in der Praxis verwirrend ist und zu Problemen führen kann, dass dieser Parameter nicht kommuniziert wird und Module "herumraten" müssen.


Zusätzlich kommt hinzu, dass die in der API-Doc angegebene ID nicht dem entspricht, was über den "type" gesendet wird. Beispiel: "vopStartCommand" gibt als Message-ID "vopStartCommandMessage" an. Tatsächlich wird aber "vopStartCommand" gesendet (https://verona-interfaces.github.io/player/#operation-publish-vopStartCommand).

**Comment by rhenck** [comment]
Auch die Beispiel-Payloads in der Doku führen diesen Parameter nicht mit und sind dementsprechend, keine geeigeten Beispiele, imo.

**Comment by mechtelm** [comment]
Hinweis platziert in der Hauptdoku Einführung/Kommunikationsmodell

s. https://verona-interfaces.github.io/intro/modelling
