### ISSUE TITLE
XSS-Verletzlichkeit der postmessage-Kommunikation

### ISSUE THREAD

**Issue by rhenck** [verona-interfaces/player#6]
Das betrifft wahrscheinlich eher die konkrete Implementation der Verona-Module, aber ich will jetzt nicht ein Ticket in allen projekten aufmachen und vielleicht kann man auch via API-Doku Dinge verbessern.

Folgender Absatz macht mir Sorgen (https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#notes):

> Any window may access this method on any other window, at any time, regardless of the location of the document in the window, to send it a message. Consequently, any event listener used to receive messages must first check the identity of the sender of the message, using the origin and possibly source properties. **This cannot be overstated: Failure to check the origin and possibly source properties enables cross-site scripting attacks.**

Module müssten, meinem Verständnis nach, eine Überprüfung machen, ob die Message, die sie verarbeiten (z.B. auch via JSON.parse()), auch tatsächlich von dem erwarteten Sender (bspw. Testcenter) kommt. Die API könnte vllt dazu zwingen.

Ich weiß auch nicht, was wir da konkret am besten machen, aber ich glaube das können wir nicht ignorieren.

**Comment by mechtelm** [comment]
Hinweis platziert in der Hauptdoku Einführung/Kommunikationsmodell

s. https://verona-interfaces.github.io/intro/modelling
