### ISSUE TITLE
restorePoint als [object] nicht [string]

### ISSUE THREAD

**Issue by HoffmannP** [verona-interfaces/player#7]
Da die gesamte Übermittlung des Message-Objekts als stringified-JSON erfolgt finde ich es absolut unpraktisch das die in `restorePoint` übermittelten Daten noch einmal stringified werden sollen. Ich schlage daher vor den Typ dieses Attributs in ein generalisiertes Objekt zu ändern.
Im Zuge einer noch zu spezifizierenden Auswertevorschriften, adaptivem Testen, der Übermittlung von Logdaten, etc. wird der Inhalt des Knotens in Zukunft auch nicht (mehr) unangetastet vom Testcenter zwischen Player und Speicher (Datenbank) hin- und hergereicht werden.

**Comment by mechtelm** [comment]
1. Wenn man Host-seitig nach Auspacken der Message den restorePoint (und analog die responses) irgendwohin legt oder zum Server schickt oder sich wiederholt, muss es String bzw. Text sein. Es ist egal, ob der Player das Stringifizieren vornimmt oder der Host. Man muss es halt nur festlegen. Als Programmierer des Host könnte man auf Nummer sicher gehen und stets stringifizieren, egal ob der Player einen String schickt oder nicht. So gesehen ist Dein Vorschlag plausibel.

2. Sobald der Host Antworten verstehen oder gar interpretieren soll, müssen wir die Schnittstelle um wohldefinierte Daten erweitern. Das sollten wir jetzt nicht in die Black-Box-Daten restorePoint und responses reinpacken.
