### ISSUE TITLE
Genauere Erklärung presentationComplete, responsesGiven, response, responseConverter und responseComplete

### ISSUE THREAD

**Issue by HoffmannP** [verona-interfaces/player#8]
Leider ist mir immer noch nicht ganz klar für was die Knoten `presentationComplete` und `responsesGiven` in der `StartedNotification` gebraucht werden. Hier würde ich mich über eine Erläuterung sehr freuen.
Komplett unverständlich sind für mich `response`, `responseConverter` und `responseComplete`.

**Comment by mechtelm** [comment]
1. presentationComplete: Teilt dem Host mit, ob die Inhalte vollständig präsentiert wurden. Das ist z. B. nötig, wenn man das Weiterblättern verhindern will bevor die Audio-Sequenz vollständig abgespielt wurde. Uns hat es auch geholfen zu bemerken, dass die Testperson einige Seiten der Unit noch nicht angeschaut hat oder noch nicht bis zum Ende der Seite gescrollt hat. Auch dann haben wir das Weiterblättern verhindert bzw. eine Warnung ausgegeben. Man kann manchmal die Seite nicht zuverlässig so gestalten, dass bemerkt wird, dass es unten auf der Seite noch zwei weitere Aufgaben gibt.

2. responsesGiven: Ist in Befragungen mit Validierung der Antworten wichtig. Solange der Player nicht meldet, dass vollständig geantwortet wurde, geht's nicht weiter. In Kompetenztests ist das nicht so wichtig, hier könnte man vielleicht einen Log-Eintrag generieren, wenn sich jemand für das Antwortverhalten interessiert.

3. response und restorePoint: Die Annahme hier ist, dass es Zustände der Unit gibt, die man beim Zurückblättern wiederherstellen will, die aber nicht Teil der Antwort sind. Z. B. hat jemand eine Audio-Sequenz zur Hälfte abgespielt und das System erlaubt die Fortsetzung nach dem Wiederaufruf. Oder die Markierung presentationComplete, also das "Wurde gesehen" verschiedener Seiten. Das ist uninteressant für die Auswertung (also nicht Teil der response), muss aber dem Player beim Wieder-Start mitgeteilt werden. Response ist also eng gedacht als alles Relevante für die Auswertung, restorePoint ist nur eine Zustandsbeschreibung von UI-Elementen. Das mag oft dasselbe sein, aber mitunter halt nicht. Der Player bekommt nach dem Laden NICHT die vorher gegebenen Antworten, sondern den RestorePoint.

4. responseConverter: Eine ID, die bei der Auswertung klarstellt, wer die response geschickt hat. Da die Struktur der response-Daten bei der Auswertung nicht bekannt ist, muss es einen Marker geben, der bestimmten Code zuweist für die Antwortverarbeitung. Wir haben im Moment eine Befragung zu laufen, wo die Antworten echt abenteuerlich strukturiert sind. Das macht nichts, wenn man durch die ID des responseConverters Bescheid weiß.

**Comment by HoffmannP** [comment]
@mechtelm Kannst du das in die Beschreibung einfügen?

**Comment by HoffmannP** [comment]
Zu `presentationComplete`: Können wir das in ein Bool umwandeln?
zu `responsesGiven`: Evtl ändern in `allResponsesGiven: boolean`? Oder die Keywords auch mit einem `#` versehen?
