### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by HoffmannP** [verona-interfaces/player#9]
Die aktuelle Version der Navigation ist eine Abschrift des letzten Entwurfs [Vo interface Item-Player](Drafts/Vo interface Item-Player v1.pdf).
Ich schlage vor
1. `NavigateToPage.newPage` in `target` umzubenennen.
2. `PageNavigationRequest.navigationTarget` in `target` umzubenennen und die Schlüsselwörter zu entfernen oder die Notwendigkeit zu erklären.
3. `UnitNavigationRequest.navigationTarget` in `direction` umzubenennen und einzig die Schlüsselwörter `#previous` und `#next` zuzulassen.

Zu 2.: Da sowohl Player als auch Testcenter über `ChangedDataTransfer.validPages` konstant synchrones Wissen über die in einer Unit enthaltenen und ansteuerbaren subunits/ teilen sehe ich keine Notwendigkeit für die Schlüsselwörter. Insbesondere, da das Testcenter ohne internes Wissen über die Unit anhand des `validPages`-Knotens die Schlüsselwörter zwar technisch auflösen kann (und nach der aktuellen Definition von `NavigateToPage.newPage` auch muss) aber keine eigene Entscheidungskompetenz dazu hat.

Zu 3.: Da das Item keinerlei Informationen über das gesamte Assessment hat ist mir unklar aufgrund welcher Umstände überhaupt eine gültige Unit-Kennung existieren sollte. Des weiteren finde ich eine andere Navigation als weiter/zurück sollte keine Entscheidung des Players sein. Außerdem ist mir unklar was **(unit)** und **(booklet) #end* bei der Spezifikation der Schlüsselwörter bedeuten soll.

**Comment by mechtelm** [comment]
1. ok

2. #next und #previous ist eingeführt, weil es vielleicht doch von äußeren Umständen im Host abhängt, welche die nächste Seite ist. Der Fall ist im Moment noch konstruiert, also ich habe keinen konkreten Fall, so gesehen können wir das auch erstmal weglassen.

3. Diese Navigationsanfragen setzt ein Player ab, wenn ein entsprechender Button auf seiner Seite geklickt wird. 
#end: Wenn der geklickt wird, wird der Test (also das booklet) als bearbeitet markiert und gesperrt.
#previous/#next: Wird benutzt, wenn die globale Navigation aus Platzgründen ausgeblendet wird und das Blättern zu anderen Units durch den Player übernommen werden soll. Das ist das übliche Szenario z. B. im DIPF-ItemBuilder. Ich finde das ungünstig, da es die Wiederverwendbarkeit der Units einschränkt, aber das ist auch in einer aktuellen Befragung bei uns eine Anforderung.
<unit>: Ja auch hier ist die Verwendbarkeit der Units auf ein spezielles Booklet beschränkt, aber wohl mitunter notwendig, zu einer spezifischen Unit zu springen.

**Comment by paflov** [comment]
- 1 und 2 - Stimme auch zu
- 3 - Wen ich richtig verstehe, was #end macht, nämlich den test komplett beenden, würde ich vorschlagen einen separaten message type zu verwenden. Dann könnte man für auch einen integer für `direction` verwenden (und müsste nicht prüfen ob das Schlüsselwort legal ist) - 1 heißt eins vor, - 1 eins zurück, - 3 drei zurück (falls vorhanden, sonst aufs erste usw.

**Comment by HoffmannP** [comment]
3. zerfällt in mehrere Teilaspekte
    1. Umbenennen von `navigationTarget` in `direction`
    1. `#previous`/`#next` weiterhin nutzen
        1. Umbenennen in `-1`/`(+)1`
        1. Relative Unit-Navigation vom Player aus erlauben (z.B. durch Nutzung von 3.1.a über signed integer als Wert für `navigationTarget`)
    1. absolute Unit-Navigation vom Player aus erlauben
    1. Beenden des Tests vom Player aus erlauben

**Comment by HoffmannP** [comment]
3.
    1. macht nur Sinn wenn iii und ii abgelehnt werden
    1. scheint unstrittig für den Fall, dass der Player die unit-interne Navigation übernimmt und die Nutzerin am Ende bzw. rückwärts gehend am Anfang angekommen ist. Das erscheint mir sinnvoll und notwendig.
        1. finde ich persönlich nicht so schön aber ist Geschmacksache
        1. kann ich mir in der Implementierung nicht als sinnvoll vorstellen, warum sollte der Player einen größeren Sprung initialisieren wollen? Welches Navigationselement würde das ermöglichen?
    1. in welchem Schritt wird die Player-Navigation über die im Booklet vorhandenen Units informiert? Ich lehne das ab weil damit imho das Sandboxing des Players überwunden wird.
    1. Argument wie iii

Die ganze Frage dreht sich vor allem darum ob wir jetzt technisch unterstützen wollen, dass sowas möglich ist. Es steht außer Frage, dass sinnvolle Tests mit dieser Funktion vorstellbar sind. In der Doku müsste vermerkt werden, dass das unüblich ist aber halt funktioniert.
Möglich wäre auch darauf zu warten, dass die Funktionalität benötigt wird und dann wieder zu diskutieren.
Außerdem könnte die VPID sowas wie eine AddOn-Definition enthalten (hatten wir im Zusammenhang mit weiteren Fähigkeiten des Testcenters wie der Bereitstellung eines Taschenrechners schon überlegt). Z.B. durch einen optionalen `target`-Parameter der eben diese absoluten `UnitNavigationRequests` ermöglicht. Ein Testcenter ohne dieses AddOn hätte damit auch einen Fallback. Diese AddOn-Fähigkeit wäre gesondert im Player/Booklet/Testcenter vermerkt und würde klar stellen, dass damit die "reine Lehre" verlassen wird.
Ich würde gerne verhindern, dass die Verantwortlichkeiten zwischen Player und Testcenter verwischen da ich diese für einen wertvollen Vorteil des ganzen Konstrukt ansehe.
